$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "positioning"
require "support/active_record"

require "minitest/hooks/test"
require "minitest/autorun"
require "mocha/minitest"

require_relative "models/list"
require_relative "models/item"
require_relative "models/optimistic_locking_item"
require_relative "models/timestamps_item"
require_relative "models/new_item"
require_relative "models/default_scope_item"
require_relative "models/composite_primary_key_item"
require_relative "models/product"
require_relative "models/category"
require_relative "models/categorised_item"
require_relative "models/author"
require_relative "models/author/student"
require_relative "models/author/teacher"
require_relative "models/blog"
require_relative "models/post"
require_relative "models/entity"
